baseURL = "https://pandora.sh/"
languageCode = "en-us"
title = "Pandora's box"
theme = "hello-friend"
paginate = 3

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 3
  showReadingTime = false

[languages]
  [languages.en]
    title = "Pandora's Box"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Pandora's Box"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "Research"
        name = "Research"
        url = "/research"
